services:
  db:
    image: postgres:16
    container_name: graveyard-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: graveyard_db
    ports:
      - "5432:5432"
    volumes:
      - graveyard_pgdata:/var/lib/postgresql/data

volumes:
  graveyard_pgdata:
